apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-http
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.service.http.svc_annotations | indent 4 }}
spec:
  type: {{ .Values.service.http.serviceType }}
  {{- if eq .Values.service.ssh.serviceType "LoadBalancer" }}
  {{- if .Values.service.ssh.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.ssh.loadBalancerIP }}
  {{- end }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.http.port }}
    {{- if  .Values.service.http.nodePort }}
    nodePort: {{ .Values.service.http.nodePort }}
    {{- end }}
    targetPort: {{ .Values.service.http.port }}
  selector:
    app: {{ template "fullname" . }}
